export const ProjectUrls = {
  home: "/",
  signIn: "/sign-in",
  signUp: "/sign-up",
  signUpVerify: "/sign-up-verify",
  signUpSuccess: "/sign-up-success",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  resetPasswordSent: "/reset-password-sent",
  resetPasswordSuccess: "/reset-password-success",
  createTrainingPlan: "/training-plans/create",
  trainingPlans: "/training-plans",
  trainingPlan: (id: string) => `/training-plans/${id}`,
  trainingPlanSession: (id: string) => `/training-plans/${id}/session`,
  trainingHistory: "/training-history",
  settings: "/settings",
} as const;
